### ISSUE TITLE
可以介绍一下项目的测试运行环境嘛

### ISSUE THREAD

**Issue by SzLeaves** [zhixiaobai/Python-zhihuishu#5]
我刚刚在python3.10下运行测试，在解析recruitAndCourseId时报如下错误：
（运行脚本名字我改了）
```python
Traceback (most recent call last):
  File "/home/szhou/git/Python-zhihuishu/zhidao.py", line 190, in <module>
    "secretStr": aes.encryptFromString(str(data))
  File "/home/szhou/git/Python-zhihuishu/AES.py", line 169, in encryptFromString
    return self.__encrypt()
  File "/home/szhou/git/Python-zhihuishu/AES.py", line 173, in __encrypt
    aes = AES.new(self.key, self.mode, self.iv)
  File "/home/szhou/.local/lib/python3.10/site-packages/Crypto/Cipher/AES.py", line 95, in new
    return AESCipher(key, *args, **kwargs)
  File "/home/szhou/.local/lib/python3.10/site-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/home/szhou/.local/lib/python3.10/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```

不过我在python3.9下运行没有发现此问题，可以说明一下运行和测试的环境嘛 :)

**Comment by zhixiaobai** [comment]
py3.9

**Comment by zhixiaobai** [comment]
我是py3.9 没问题

**Comment by SzLeaves** [comment]
好的，建议在README里面写清楚运行环境，我看了一下可能跟py3.10的解析对象有关
